swagger: "2.0"
info:
  description: Transupport API to pull information from google sheets
  version: "1.0.0"
  title: DSS Swagger Config
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - people
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of people to get from people
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
    post:
      operationId: people.create
      tags:
        - people
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person in list

  /people/{lname}:
    get:
      operationId: people.read_one
      tags:
        - people
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string

    delete:
      operationId: people.delete
      tags:
        - people
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: lname
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a person from people list
  /accounts:
    get:
      operationId: accounts.getAccounts
      tags:
        - accounts
      summary: Gets accounts
      description: Gets accounts with flag = all, resolved, late, at_risk, cancelled, non_resolved
      parameters:
        - name: include
          in: query
          type: string
          required: True
      responses:
        200:
          description: Successfully read priority accounts
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                product_code:
                  type: string
                style_number:
                  type: string
                ETA:
                  type: string
                customer:
                  type: string
                status:
                  type: string
                quantity:
                  type: integer
    post:
      operationId: accounts.send_email
      tags:
        - account
      summary: send email with account information
      description: After a transport method is selected, send an email to required recipient to move order forward
      parameters:
        - name: email
          in: body
          description: email recipient, body, and subject
          required: True
          schema:
            type: object
            properties:
              recipient:
                type: string
                description: email recipient
              subject:
                type: string
                description: email subject
              body:
                type: string
                description: email body
      responses:
        200:
          description: Successfully send email
  /accounts/count:
    get:
      operationId: accounts.getCounts
      tags:
        - accounts
      summary: Gets account counts
      description: Get the counts of all accounts
      responses:
        200:
          description: Successfully read all counts
          schema:
            type: object
            properties:
              at_risk:
                type: integer
              cancelled:
                type: integer
              late:
                type: integer
              resolved:
                type: integer
              not_ready:
                type: integer
  /acount/{id}:
    get:
      operationId: accounts.get_account_details
      tags:
        - account
      summary: get specific account details
      description: get specific details of an account by id
      parameters:
        - name: id
          in: path
          description: id of account
          type: integer
          required: True
      responses:
        200:
          description: Successfully read account details
    put:
      operationId: accounts.set_transportation
      tags:
        - account
      summary: add the transportation choice to sheet
      description: update transportation of account by id
      parameters:
        - name: id
          in: path
          description: id of account to update
          type: integer
          required: True
        - name: method
          in: body
          description: transportation choice
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              number:
                type: integer
      responses:
        200:
          description: Successfully updated transportation methods
