swagger: "2.0"
info:
  description: Transupport API to pull information from google sheets
  version: "1.0.0"
  title: Transupport Swagger Config
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

# Paths supported by the server application
paths:
  /accounts:
    get:
      operationId: accounts.getAccounts
      tags:
        - accounts
      summary: Gets accounts
      description: Gets accounts with flag = all, resolved, late, at_risk, cancelled, non_resolved
      parameters:
        - name: include
          in: query
          type: string
          required: True
      responses:
        200:
          description: Successfully read priority accounts
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                product_code:
                  type: string
                style_number:
                  type: string
                ETA:
                  type: string
                customer:
                  type: string
                status:
                  type: string
                quantity:
                  type: integer
    post:
      operationId: accounts.send_email
      tags:
        - account
      summary: send email with account information
      description: After a transport method is selected, send an email to required recipient to move order forward
      parameters:
        - name: email
          in: body
          description: email recipient, body, and subject
          required: True
          schema:
            type: object
            properties:
              recipient:
                type: string
                description: email recipient
              subject:
                type: string
                description: email subject
              body:
                type: string
                description: email body
      responses:
        200:
          description: Successfully send email
  /accounts/count:
    get:
      operationId: accounts.getCounts
      tags:
        - accounts
      summary: Gets account counts
      description: Get the counts of all accounts
      responses:
        200:
          description: Successfully read all counts
          schema:
            type: object
            properties:
              at_risk:
                type: integer
              cancelled:
                type: integer
              late:
                type: integer
              resolved:
                type: integer
              not_ready:
                type: integer
  /acount/{id}:
    get:
      operationId: accounts.get_account_details
      tags:
        - account
      summary: get specific account details
      description: get specific details of an account by id
      parameters:
        - name: id
          in: path
          description: id of account
          type: integer
          required: True
      responses:
        200:
          description: Successfully read account details
    put:
      operationId: accounts.set_transportation
      tags:
        - account
      summary: add the transportation choice to sheet
      description: update transportation of account by id
      parameters:
        - name: id
          in: path
          description: id of account to update
          type: integer
          required: True
        - name: method
          in: body
          description: transportation choice
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              number:
                type: integer
      responses:
        200:
          description: Successfully updated transportation methods
